version: "3.2"

services:
  db2:
    build:
      context: ./database
    image: mysql-bcore
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: brite-core
      MYSQL_DATABASE: payments
    volumes:
      - "./database/conf:/etc/mysql/conf.d"
      - "sqldata:/var/lib/mysql"
volumes:
  sqldata:
